definitions:
  main.PostReq:
    properties:
      name:
        type: string
    type: object
  main.ReturnMessage:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
info:
  contact: { }
  description: 我的 gin swagger API 描述
  title: 我的 gin swagger API
  version: "1.0"
paths:
  /api/get/{id}:
    get:
      parameters:
        - description: ID 信息
          in: path
          name: id
          required: true
          type: string
        - description: 第几页数据
          in: query
          name: page
          type: integer
        - description: 每页多少条数据
          in: query
          name: size
          type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ReturnMessage'
      security:
        - ApiToken: [ ]
      summary: 一个 get 请求
      tags:
        - 组1
  /api/post/{id}:
    post:
      parameters:
        - description: ID
          in: path
          name: id
          required: true
          type: string
        - description: JSON数据
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/main.PostReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ReturnMessage'
      summary: 一个 post 请求
      tags:
        - 组2
  /api/post/formdata:
    post:
      parameters:
        - description: 姓名
          in: formData
          name: name
          required: true
          type: string
        - description: 需要上传的文件
          in: formData
          name: upload_file
          required: true
          type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ReturnMessage'
      summary: 需要 formdata 参数
      tags:
        - 组2
securityDefinitions:
  ApiToken:
    in: header
    name: X-Token
    type: apiKey
swagger: "2.0"
